name: Workflow Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  automate-task:
    runs-on: ubuntu-latest

    env:
      env: ${{ vars.APIKEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Echo the API Key
      run: echo "API_KEY is: $API_KEY"
