name: Run apt update and echo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Run apt update
        run: sudo apt update

      - name: Echo Hello World
        run: echo "Hello, World"
